"""create_device_config

Revision ID: aaed7575eb1f
Revises: 51052f913218
Create Date: 2026-10-02 15:09:28.416343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaed7575eb1f'
down_revision = '51052f913218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wifi_ssid', sa.String(length=100), nullable=False),
    sa.Column('wifi_password', sa.String(length=100), nullable=False),
    sa.Column('server_url', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_config')
    # ### end Alembic commands ###
