"""Added fields for 15 min rule

Revision ID: b1c97ca01a4e
Revises: aaed7575eb1f
Create Date: 2026-10-04 15:01:01.669694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1c97ca01a4e'
down_revision = 'aaed7575eb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_config')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('enrollment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('committee', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('attendance', sa.String(length=20), nullable=True))

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('enrollment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('committee', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('committee')
        batch_op.drop_column('role')
        batch_op.drop_column('enrollment')
        batch_op.drop_column('name')

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_column('attendance')
        batch_op.drop_column('committee')
        batch_op.drop_column('role')
        batch_op.drop_column('enrollment')
        batch_op.drop_column('name')

    op.create_table('device_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wifi_ssid', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('wifi_password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('device_config_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('device_config_pkey'))
    )
    # ### end Alembic commands ###
